version: '3'
services:
  mongo:
    image: 'mongo:latest'
    restart: always
  redis:
    image: 'redis:latest'
  api:
    build:
      context: ./server/
      dockerfile: Dockerfile.dev
    volumes:
      - /code/node_modules
      - ./server:/code
    ports:
       - '8081:5000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGOHOST=mongo
      - MONGODB_NAME=frappuccino
      - MONGODB_TEST=frappuccino_test
      - MONGOPORT=27017
      - EXPRESS_SESSION_KEY=frappuccino
      - EXPRESS_SESSION_SECRET=zxc90zxc
    depends_on:
      - mongo
  web:
    stdin_open: true
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    volumes:
      - /code/node_modules
      - ./client:/code
  proxy:
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
    depends_on:
      - api
      - web
